[package]
name = "graphics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
env_logger = "0.10.1"
glam = "0.24.2"
image = "0.24.7"
libc = "0.2.151"
log = "0.4.20"
obj-rs = "0.7.1"
